# Undergraduate and visiting trainees, newest first.
- { name: Colin Chung Kai Yuan, year: 2025, from: "Faculty of Science, NUS" }
- { name: Nicole Ng Chyi Shien, year: 2024, from: "Faculty of Science, NUS" }
- { name: Keisha Mayra, year: 2024, from: "Amgen Scholar, Universitas Padjadjaran" }
- { name: Chia Jin Quan, year: 2024, from: "Faculty of Science, NUS" }
- { name: Lim Yee Huan, year: 2024, from: "Faculty of Science, NUS" }
- { name: Miguel Soon Jun Yi, year: 2023, from: "Faculty of Science, NUS" }
- { name: Sharifah Lubna Binte Mohammad Isa, year: 2023, from: "Faculty of Science, NUS" }
- { name: Elaine Sng Shi Min, year: 2023, from: "Faculty of Science, NUS" }
- { name: Audrey Santoso, year: 2023, from: "Amgen Scholar, Universitas Padjadjaran" }
- { name: Chu Ho Lun Collin, year: 2023, from: "School of Medicine, NUS" }
- { name: Tang Guang Xiang, year: 2023, from: "School of Medicine, NUS" }
- { name: Hon Yu Han Raphael, year: 2023, from: "School of Medicine, NUS" }
- { name: Liu Yao, year: 2023, from: "Faculty of Science, NUS" }
- { name: "Wong Lyn Ee, Rachel", year: 2023, from: "Faculty of Science, NUS" }
- { name: Metta Sodian, year: 2022, from: "Amgen Scholar, Atma Jaya Catholic University of Indonesia" }
- { name: "Wong Ming Hui, Millie", year: 2022, from: "Faculty of Science, NUS" }
- { name: "Ng De Rong, Tony", year: 2021, from: "School of Medicine, NUS" }
- { name: Ng Yi Jie, year: 2021, from: "Faculty of Science, NUS" }
- { name: Chan Ee Ling Jann, year: 2021, from: "Faculty of Science, NUS" }
- { name: Eugene Gan Cheong Wei, year: 2021, from: "Faculty of Science, NUS" }
- { name: Tay Hui Yi, year: 2021, from: "Faculty of Science, NUS" }
- { name: Ng Jing Ting, year: 2021, from: "Faculty of Science, NUS" }
- { name: Elaine Tiong Pei Ying, year: 2021, from: "Faculty of Science, NUS" }
- { name: Tan Huai Chyi, year: 2021, from: "Faculty of Science, NUS" }
- { name: Stella Lee Yue Ting, year: 2020, from: "Faculty of Science, NUS" }
- { name: Daniel Chua Chong Hin, year: 2019, from: "Faculty of Science, NUS" }
- { name: Lisa Yu, year: 2019, from: "Amgen Scholar, Cornell University" }
- { name: Drake Alexis Mei Ern, year: 2019, from: "University of North Carolina at Chapel Hill" }
- { name: Michelle Pang Wan Sia, year: 2019, from: "Faculty of Science, NUS" }
